### ISSUE TITLE
This version of ChromeDriver only supports Chrome version 90

### ISSUE THREAD

**Issue by wisebearlu** [DedInc/selenium_dolphin#11]
I checked, the chromedrive auto downloaded is 122. I see the launched anty browser is also 122. why this error?

python ts.py
Downloading the driver... [##############################] 38.06/38.06MB
Download completed.
Traceback (most recent call last):
  File "C:\do\auto\dolphin\ts.py", line 32, in <module>
    driver = dolphin.get_driver(options=options, port=port)
  File "C:\do\auto\dolphin\selenium_dolphin\selenium_dolphin.py", line 123, in get_driver
    driver = webdriver.Chrome(service=Service(driver_path), options=options)
  File "C:\Users\Ch\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
  File "C:\Users\Ch\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 61, in __init__
    super().__init__(command_executor=executor, options=options)
  File "C:\Users\Ch\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "C:\Users\Ch\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "C:\Users\Ch\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Ch\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:2232
from session not created: This version of ChromeDriver only supports Chrome version 90
Current browser version is 122.0.6261.49

**Comment by DedInc** [comment]
Check the directory, maybe you have a chrome driver next to you is not the same version as anty, conflicts, because I have double-checked everything and everything works fine, note that I have Windows and if you have another OS there may be errors, because I do not have the ability to test and fix it all yet
